#!/bin/bash
# Create the directory
mkdir /tmp/my_first_directory
# Check if the directory was created successfully
if [ -d "/tmp/my_first_directory" ]; then
    echo "Directory created successfully."
    file /tmp/my_first_directory
else
    echo "Failed to create directory."
fi
