#!/bin/bash
# Create the directory
mkdir /tmp/my_first_directory
# Check if the directory was created successfully
# Check if the directory was created successfully
if [ $? -eq 0 ]; then
    echo "Directory created successfully."
    file /tmp/my_first_directory/
else
    echo "Failed to create directory."
fi
